### PR TITLE
Refactor cronjob deployment

### PR DESCRIPTION
**Pull request by teluq-pbrideau**
As a sysadmin, I prefer to have the cronjobs in the `/etc/cron.d` directory, as a cron in the root user config is confusing when searching on a server.

I do not know how should we define the migration step in the `config.pp`...
```puppet
cron { 'update-repos':
  ensure => absent
}
```

My guess is it should be documented in the readme to add the `ensure=>absent`, and not to clutter the code with breaking updates.

Aslo, I want to be able to modify the time this job should run at.

### CODE REVIEW

**Comment by bp85** [comment]
@teluq-pbrideau Thanks for bringing this to my attention. `/etc/cron.d` format is considered a legacy way for managing cronjob, but I agree that as a sysadmin, I tend to keep certain things there.
I've added a new variable `legacy_cron`, setting it to true will create cronjob in `/etc/cron.d`. Hopefully this way existing ones won't break and there's an option to move to old format if needed.
Here's the relevant commit https://github.com/bp85/puppet-mirror_repos/commit/8551ec3b429e1ddba11b0285a41d150cfea6184c

```diff
diff --git a/manifests/config.pp b/manifests/config.pp
index 7ddaf75..edccf60 100644
--- a/manifests/config.pp
+++ b/manifests/config.pp
@@ -29,15 +29,37 @@ class mirror_repos::config {
     mode    => '0755',
     content => template('mirror_repos/update-repos.sh.erb'),
   }
-  #run cron every night to update repos
-  cron::job { 'update-repos':
-    command => '/usr/sbin/update-repos',
-    user    => 'root',
-    require => File['/usr/sbin/update-repos'],
-    minute  => $mirror_repos::cron_minute,
-    hour    => $mirror_repos::cron_hour,
-    date    => $mirror_repos::cron_date,
-    month   => $mirror_repos::cron_month,
-    weekday => $mirror_repos::cron_weekday,
+
+  #If legacy cron job (/etc/cron.d) is preferred
+  if $mirror_repos::legacy_cron {
+    #run cron every night to update repos
+    cron::job { 'update-repos':
+      command => '/usr/sbin/update-repos',
+      user    => 'root',
+      require => File['/usr/sbin/update-repos'],
+      minute  => $mirror_repos::cron_minute,
+      hour    => $mirror_repos::cron_hour,
+      date    => $mirror_repos::cron_date,
+      month   => $mirror_repos::cron_month,
+      weekday => $mirror_repos::cron_weekday,
+    }
+
+    # disable crontab job
+    cron { 'update-repos':
+      ensure  => absent,
+      command => '/usr/sbin/update-repos',
+      user    => 'root',
+    }
+  } else {
+    cron { 'update-repos':
+      command => '/usr/sbin/update-repos',
+      user    => 'root',
+      hour    => $mirror_repos::cron_hour,
+      minute  => $mirror_repos::cron_minute,
+      date    => $mirror_repos::cron_date,
+      month   => $mirror_repos::cron_month,
+      weekday => $mirror_repos::cron_weekday,
+      require => File['/usr/sbin/update-repos'],
+    }
   }
 }
diff --git a/manifests/init.pp b/manifests/init.pp
index 7bc658b..35bb6e0 100644
--- a/manifests/init.pp
+++ b/manifests/init.pp
@@ -41,6 +41,7 @@ class mirror_repos (
     String $config_dir    = $mirror_repos::params::config_dir,
     String $repos_dir     = $mirror_repos::params::repos_dir,
     Boolean $manage_vhost = $mirror_repos::params::manage_vhost,
+    Boolean $legacy_cron  = $mirror_repos::params::legacy_cron,
     String $cron_minute   = $mirror_repos::params::cron_minute,
     String $cron_hour     = $mirror_repos::params::cron_hour,
     String $cron_date     = $mirror_repos::params::cron_date,
diff --git a/manifests/params.pp b/manifests/params.pp
index 11b6d83..6d00e6b 100644
--- a/manifests/params.pp
+++ b/manifests/params.pp
@@ -8,6 +8,7 @@ class mirror_repos::params {
               $config_dir   = '/etc/mirror.repos.d'
               $repos_dir    = '/repos'
               $repos        = {}
+              $legacy_cron  = false,
               $cron_minute  = '0'
               $cron_hour    = '1'
               $cron_date    = '*'
```

**Comment by teluq-pbrideau** [comment]
@bp85 Thanks for merging.
it’s the first time I hear `/etc/cron.d` called a legacy feature.
Can you point me to a source where I can learn about this? Cron `manpage` does not mention it is a legacy feature.  In fact, I thought it was the other way around: the `xxx.d` directory were added after it was cumbersome to have all configs in one file.
You tell me the recommended way to manage cronjobs is via `/etc/crontab`?

**Comment by teluq-pbrideau** [comment]
Oh, searching deeper, the `cron` type in puppet is not valid anymore? https://puppet.com/docs/puppet/7/cheatsheet_core_types.html

edit: nevermind.
https://puppet.com/docs/puppet/7/type.html
```
The following types are included in supported modules on the Forge. However, they are also included in the puppet-agent package, so you do not have to install them separately. See each module's README for detailed information about that type.
```
https://forge.puppet.com/modules/puppetlabs/cron_core

**Comment by teluq-pbrideau** [comment]
And now that I dig again on this, instead of depending on another module, I should probably have suggested the `target` option…
```
cron { ... :
  target => /etc/cron.d/example
  ...
}
```

**Pull request merged**
