### PR TITLE
RHEL 8  & CentOS 8 Support

### PR DESCRIPTION
**Pull request by LooOOooM**
Hej mate, can you make this official please.

### CODE REVIEW

**Comment by LooOOooM** [comment]
I tested this fix witzh puppet 6

**Review by bp85 — APPROVED** [review]

**Comment by bp85** [comment]
@LooOOooM I'm working on resolving build/deploy process as it's broken. Let me know if this is urgent, I can merge and manually upload new version to forge.

**Comment by LooOOooM** [comment]
> 
> 
> @LooOOooM I'm working on resolving build/deploy process as it's broken. Let me know if this is urgent, I can merge and manually upload new version to forge.

I don't get it what you mean by a broken build/deployment process. However even it is not super urgent to me, as I got already the fix :) I guess It would be helping all others guys hustinging with Centos 8, if you merge the fix and set it as a new version to Puppet forge :)

**Comment by bp85** [comment]
> I don't get it what you mean by a broken build/deployment process. However even it is not super urgent to me, as I got already the fix :) I guess It would be helping all others guys hustinging with Centos 8, if you merge the fix and set it as a new version to Puppet forge :)

I had a CI/CD pipeline that automatically does syntax check and push a new version to forge after merging to master. Due to some deprecations it's not working as intended, I was working on fixing it.

**Pull request merged**
